title: Bill Koppelman
logo: "/images/circle-cropped.png?raw=true" 
description: >
  Swimming Coach 
  <br>
  Sports Analytics 
  <br><br>
  <a href="https://www.linkedin.com/in/wkopp/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://twitter.com/wkopp007">Follow me on Twitter</a>
  
theme: jekyll-theme-dinky
google_analytics: UA-160173383-1
