title: Bill Koppelman
logo: "/images/circle-cropped.png?raw=true" 
description: >
  Associate Head Swimming Coach 
  <br>
  Sports Data Analytics 
  <br><br>
  <a href="https://www.linkedin.com/in/wkopp/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://twitter.com/wkopp007">Follow me on Twitter</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-160173383-1
